#ifndef SENTINEL_DEVELOPMENT_H
#define SENTINEL_DEVELOPMENT_H

#define DEVELOPMENT false
#define RUN_TESTS false
#define RUN_DATAGEN false
#define LI_CHESS_BUILD false

#endif //SENTINEL_DEVELOPMENT_H
